/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: https://sketchfab.com/artceng
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Mug(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/mug.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow geometry={nodes.Cylinder.geometry} material={materials['Material.001']} rotation={[0, 0.27, 0]} />
    </group>
  )
}

useGLTF.preload('/mug.glb')
